# Generated by Django 4.2.2 on 2023-11-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Areas',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
    ]
