# Generated by Django 4.2.2 on 2023-11-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropapp', '0002_rename_state_areas_rename_country_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Areas',
            new_name='State',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropapp.state')),
            ],
        ),
    ]
