# Generated by Django 4.2.2 on 2023-11-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropapp', '0003_rename_district_country_rename_areas_state_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='District',
        ),
    ]
